name: flutter_w_log
description: A logging framework developed in fluent provides a fast and simple logging solution. All logs are saved to the database and can be exported as local files.
version: 0.0.8
homepage: https://github.com/jawa0919/flutter_w_log

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  stack_trace: ">=1.0.0 <2.0.0"

  sembast: ">=3.0.0 <4.0.0"
  sembast_web: ">=2.0.0 <3.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  path: ">=1.0.0 <2.0.0"
  xxtea: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
